version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    entrypoint: ["npm", "run", "start:dev"]
  db:
    image: bitnami/mongodb:5.0.17
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=123456
      - MONGODB_DATABASE=nest
    



